# Generated by Django 3.1.4 on 2021-01-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201225_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='money',
            field=models.FloatField(default=500),
        ),
    ]
