# Generated by Django 3.1.4 on 2021-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transfers_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='accountNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
