# Generated by Django 3.1.4 on 2021-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210108_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='accountNumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
