# Generated by Django 3.1.4 on 2021-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210108_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='accountNumber',
        ),
        migrations.AlterField(
            model_name='transfers',
            name='money',
            field=models.FloatField(default=50000),
        ),
    ]
